const ActionTypes = {
  'SET_CANVAS_LAYOUT' : 'SET_CANVAS_LAYOUT',
  'USER_CLICK' : 'USER_CLICK',
  'LOGIN' : 'LOGIN',
  'LOGIN_REQUEST' : 'LOGIN_REQUEST',
  'LOGIN_SUCCESS' : 'LOGIN_SUCCESS',
  'LOGIN_FAILED' : 'LOGIN_FAILED',
  'USER_JOIN' : 'USER_JOIN',
  'USER_LEAVE' : 'USER_LEAVE',
  'USER_CLICKED' : 'USER_CLICKED',
  'SET_MY_USER_ID' : 'SET_MY_USER_ID'
};

export default ActionTypes;
